const icons = {
  google: require("../assets/icons/google.png"),
  home: require("../assets/icons/home.png"),
  search: require("../assets/icons/search.png"),
  person: require("../assets/icons/person.png"),
  bell: require("../assets/icons/bell.png"),
  filter: require("../assets/icons/filter.png"),
  star: require("../assets/icons/star.png"),
  heart: require("../assets/icons/heart.png"),
  backArrow: require("../assets/icons/back-arrow.png"),
  calendar: require("../assets/icons/calendar.png"),
  info: require("../assets/icons/info.png"),
  language: require("../assets/icons/language.png"),
  logout: require("../assets/icons/logout.png"),
  people: require("../assets/icons/people.png"),
  shield: require("../assets/icons/shield.png"),
  wallet: require("../assets/icons/wallet.png"),
  rightArrow: require("../assets/icons/right-arrow.png"),
  send: require("../assets/icons/send.png"),
  bed: require("../assets/icons/bed.png"),
  bath: require("../assets/icons/bath.png"),
  area: require("../assets/icons/area.png"),
  chat: require("../assets/icons/chat.png"),
  phone: require("../assets/icons/phone.png"),
  carPark: require("../assets/icons/car-park.png"),
  cutlery: require("../assets/icons/cutlery.png"),
  dog: require("../assets/icons/dog.png"),
  dumbell: require("../assets/icons/dumbell.png"),
  laundry: require("../assets/icons/laundry.png"),
  run: require("../assets/icons/run.png"),
  swim: require("../assets/icons/swim.png"),
  wifi: require("../assets/icons/wifi.png"),
  location: require("../assets/icons/location.png"),
  edit: require("../assets/icons/edit.png"),
};

export default icons;
